BGT citygml loader
B3Partners/brmo pull request #1114
Opened 2021-07-02 12:45 UTC by matthijsln

2021-07-26 11:54 UTC, mprins requested changes
Ik zie weinig waarde in Engelstalige documentati en wat mij betreft mogen nieuwe modules zoals deze onder MIT licentie (zie ook https://b3partners.slack.com/archives/C98HH2BP1/p1618574229019100 )

Ik zal de pom files even fixen.

2021-07-26 12:44 UTC, mprins commented on bgt-loader/pom.xml
> +      <groupId>com.google.code.findbugs</groupId>
toch wel in gegenereerde code

2021-07-26 12:46 UTC, mprins commented
een "echte" integratie test met een stukje echte data (al dan niet met downloaden vanuit extern/pdok) zou mooi zijn om onverwachte dingen als een schema aanpassing door pdok te vangen (voor de topNL hebben we dat al een paar keer  meegemaakt)

2021-07-26 17:57 UTC, matthijsln commented
> een "echte" integratie test met een stukje echte data (al dan niet met downloaden vanuit extern/pdok) zou mooi zijn om onverwachte dingen als een schema aanpassing door pdok te vangen (voor de topNL hebben we dat al een paar keer meegemaakt)

Klopt, ga die zeker nog even maken, samen met wat extra unit tests van al gedownloadde data.

2021-07-26 17:59 UTC, matthijsln commented on bgt-loader/README.md
> +createuser bgt --password bgt -P
Ik schrijf technische documentatie sneller in het Engels, vandaar ;) Maar er komt nog een Nederlandse handleiding, mogelijk dat iemand anders die ook kan schrijven en wat kan uitbreiden. Thanks voor de PostgreSQL docker, zal ik meenemen in een test workflow. Ik had op m'n Raspberry Pi al een PostgreSQL docker gebruikt, met `-c fsync=off` erbij gaat dat best snel.

2021-08-03 15:17 UTC, matthijsln commented on bgt-loader/README.md
> +createuser bgt --password bgt -P
Documentatie in README.md is nu in het Nederlands.

2021-08-05 13:55 UTC, mprins approved these changes
LGTM

ik kan evt volgende week kijken naar inbouwen in brmo-service en migratie scripts/handleiding.

2021-08-05 14:12 UTC, merged

2021-08-06 14:03 UTC, mprins commented
ben er niet blij mee dat deze PR Junit 4 herintroduceert via okhttp mock webserver...
zie oa. https://github.com/square/okhttp/issues/4667