Voeg materialized views toe die de BRK 2.0 en BAG 2.0 combineren
B3Partners/brmo pull request #1907
Opened 2023-10-11 15:37 UTC by geertoff

[BRMO-338](https://b3partners.atlassian.net/browse/BRMO-338 )

De materialized views die worden gebruikt als kaartlagen in Tailormap zijn toegevoegd. Daarnaast zijn er een aantal utiliteiten scripts toegevoegd die processen simpeler kunnen maken. 

[BRMO-338]: https://b3partners.atlassian.net/browse/BRMO-338?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ

2023-10-16 11:00 UTC, mprins requested changes
waarom worden niet overal de modelnamen gebruikt? gekke afkortingen als aand_naamgebruik of subject_identif enz. zijn niet echt behulpzaam in het begrijpen van het datamodel.

- [ ] Er ontbreekt een verwijzing naar Jira ticket
- [x] Er is (ook) geen beschrijving van de functie van de PR
- [ ] commentaar/commit is niet in Nederlands (zie: https://b3partners.github.io/brmo/developer-notes.html)
- [ ] de naamgeving+locatie van de bestanden is onjuist

2023-10-16 11:00 UTC, mprins commented on datamodel/brk/truncate-brk2.0_oracle.sql
dit is geen datamodel script; het hoort onder datamodel/utility_scripts/oracle en de naamgeving dient ook aangepast

2023-10-16 11:00 UTC, mprins commented on datamodel/brk/brk2.0_oracle_mat_views.sql
dit bestand hoort onder datamodel/extra_scripts/oracle

2023-10-16 11:00 UTC, mprins commented on datamodel/brk/brk2.0_postgresql_mat_views.sql
dit bestand ghoort onder datamodel/extra_scripts/postgres

2023-10-16 11:00 UTC, mprins commented on datamodel/brk/brk2.0_postgresql_mat_views.sql
> +    array_to_string(( SELECT array_agg(((((((((((((((((((('id: '::text || aantekening.identificatie::text) || ', '::text) || 'aard: '::text) || COALESCE(aantekening.aard, ''::character varying)::text
het casten naar text is onnodig en maat de code slecht leesbaar

2023-12-14 13:16 UTC, geertoff commented
> dit is geen datamodel script; het hoort onder datamodel/utility_scripts/oracle en de naamgeving dient ook aangepast 

Welke naam wil je dat ik dit bestand geef?

2023-12-20 09:59 UTC, closed without merging