[BRMO-351] Zakelijke rechten die direct het zakelijke rechten belasten, worden niet getoond
B3Partners/brmo pull request #2043
Opened 2024-02-20 15:48 UTC by geertoff

Een zakelijk recht, zoals een erfpacht-recht, kan een eigendomsrecht belasten. Ook is het mogelijk dat een zakelijk recht een zakelijk recht als een erfpacht kan belasten. Momenteel worden deze zakelijke rechten die direct een ander zakelijk recht belasten niet getoond. 

Voor PostgreSQL en Oracle is deze fixe toegepast.

Upgrade notities: 
Voor het toepassen van deze update hoeft enkel de DDL van de view `vb_util_zk_recht_op_koz` worden toegepast zonder overige views te droppen. Wel zouden de materialized views moeten worden ververst met [dit script](https://github.com/B3Partners/brmo/blob/master/datamodel/utility_scripts/postgresql/902_refresh_brk2.0_mat_views.sql)

2024-02-21 09:32 UTC, mprins requested changes
> Upgrade notities:
Voor het toepassen van deze update hoeft enkel de DDL van de view vb_util_zk_recht_op_koz worden toegepast zonder overige views te droppen. Wel zouden de materialized views moeten worden ververst met [dit script](https://github.com/B3Partners/brmo/blob/master/datamodel/utility_scripts/postgresql/902_refresh_brk2.0_mat_views.sql)

Dit is ontoereikend; upgrade instructies dienen onder https://github.com/B3Partners/brmo/wiki/Upgrade-Instructies te worden vastgelegd, in dit geval ws. als onderdeel van https://github.com/B3Partners/brmo/wiki/Upgrade-v3.0.2-naar-v3.0.3

Tevens is het in PostgreSQL onmogelijk een view te droppen en weer aan te maken als daar andere views van afhankelijk zijn;het aanpassen van de view dieni in het upgrade script verwerkt te worden, incl. droppen en opnieuw aanmaken van (materialized) views indien noodzakelijk.

Upgrade scripts welke voor een update worden uitgevoerd zijn te vinden onder https://github.com/B3Partners/brmo/tree/master/datamodel/upgrade_scripts voor de specifieke versie, schema en omgeving. deze scripts zijn ook vermeld in de upgrade instructies, het runnen van het script van de upgrade instructies dient voldoende te zijn voor de upgrade (upgrade van in dit geval 2.0.2 naar 2.0.3) wordt automatisch getest

2024-03-04 08:27 UTC, geertoff commented
> Dit is ontoereikend; upgrade instructies dienen onder https://github.com/B3Partners/brmo/wiki/Upgrade-Instructies te worden vastgelegd, in dit geval ws. als onderdeel van https://github.com/B3Partners/brmo/wiki/Upgrade-v3.0.2-naar-v4.0.0 

Waar in het bestand van https://github.com/B3Partners/brmo/wiki/Upgrade-v3.0.2-naar-v4.0.0 kan ik de upgrade instructies plaatsen? Onder Release?

> Tevens is het in PostgreSQL onmogelijk een view te droppen en weer aan te maken als daar andere views van afhankelijk zijn;het aanpassen van de view dieni in het upgrade script verwerkt te worden, incl. droppen en opnieuw aanmaken van (materialized) views indien noodzakelijk.

In dit geval wordt een view aangepast die met `CREATE OR REPLACE VIEW` kan worden toegepast zonder dat dit ten koste gaat van afhankelijke (materialized) views, dus dit lijkt mij niet van toepassing. 

> Upgrade scripts welke voor een update worden uitgevoerd zijn te vinden onder https://github.com/B3Partners/brmo/tree/master/datamodel/upgrade_scripts voor de specifieke versie, schema en omgeving. deze scripts zijn ook vermeld in de upgrade instructies, het runnen van het script van de upgrade instructies dient voldoende te zijn voor de upgrade (upgrade van in dit geval 2.0.2 naar 2.0.3) wordt automatisch getest 

Goed om te weten, kan ik deze wijziging van de view `vb_util_zk_recht_op_koz` dan toevoegen in het script van [postgresql upgrade script](https://github.com/B3Partners/brmo/blob/master/datamodel/upgrade_scripts/3.0.2-4.0.0/postgresql/brk.sql) en [oracle upgrade script](https://github.com/B3Partners/brmo/blob/master/datamodel/upgrade_scripts/3.0.2-4.0.0/oracle/brk.sql) plaatsen?

2024-03-08 13:47 UTC, mprins commented
> > Dit is ontoereikend; upgrade instructies dienen onder https://github.com/B3Partners/brmo/wiki/Upgrade-Instructies te worden vastgelegd, in dit geval ws. als onderdeel van https://github.com/B3Partners/brmo/wiki/Upgrade-v3.0.2-naar-v4.0.0
> 
> Waar in het bestand van https://github.com/B3Partners/brmo/wiki/Upgrade-v3.0.2-naar-v4.0.0 kan ik de upgrade instructies plaatsen? Onder Release?
> 

aangezien er geen actie te doen is (verversen van materialized views is een reguliere beheer actie, niet voorbehouden aan de upgrade) hoeft er verder geen vermelding te worden gemaakt, het staat immers als in de release notes dat de view wordt aangepast.

> > Tevens is het in PostgreSQL onmogelijk een view te droppen en weer aan te maken als daar andere views van afhankelijk zijn;het aanpassen van de view dient in het upgrade script verwerkt te worden, incl. droppen en opnieuw aanmaken van (materialized) views indien noodzakelijk.
> 
> In dit geval wordt een view aangepast die met `CREATE OR REPLACE VIEW` kan worden toegepast zonder dat dit ten koste gaat van afhankelijke (materialized) views, dus dit lijkt mij niet van toepassing.
> 
misschien heb je geluk
> > Upgrade scripts welke voor een update worden uitgevoerd zijn te vinden onder https://github.com/B3Partners/brmo/tree/master/datamodel/upgrade_scripts voor de specifieke versie, schema en omgeving. deze scripts zijn ook vermeld in de upgrade instructies, het runnen van het script van de upgrade instructies dient voldoende te zijn voor de upgrade (upgrade van in dit geval 2.0.2 naar 2.0.3) wordt automatisch getest
> 
> Goed om te weten, kan ik deze wijziging van de view `vb_util_zk_recht_op_koz` dan toevoegen in het script van [postgresql upgrade script](https://github.com/B3Partners/brmo/blob/master/datamodel/upgrade_scripts/3.0.2-4.0.0/postgresql/brk.sql) en [oracle upgrade script](https://github.com/B3Partners/brmo/blob/master/datamodel/upgrade_scripts/3.0.2-4.0.0/oracle/brk.sql) plaatsen?

idd. naast aanpassen van bronbestand (voor nieuwe releases) moet ddl voor de aangepaste view in het upgrade script voor PG en Oracle:
- https://github.com/B3Partners/brmo/blob/e42ede25afe92eee2f7293f46ce4bdb5fe88b5c8/datamodel/upgrade_scripts/3.0.2-4.0.0/postgresql/brk.sql#L11
- https://github.com/B3Partners/brmo/blob/e42ede25afe92eee2f7293f46ce4bdb5fe88b5c8/datamodel/upgrade_scripts/3.0.2-4.0.0/oracle/brk.sql#L18

2024-03-11 15:33 UTC, mprins approved these changes
misschien nog eens kijken om de substring functie uit de where clause te vervangen door een directe of berekende kolom in de tabel vanwege mogelijk betere performance, maar dat is nu niet aan de orde

2024-03-11 15:34 UTC, merged